import {
  StyleSheet,
} from 'react-native';

const Homestyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  map: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    position: 'absolute',
    zIndex: -1,
  },
  iconSearch: {
    marginLeft: 20,
  },
  imgSearch: {
    marginLeft: 20,
    width: 15,
    height: 15,
    resizeMode: 'stretch',
    alignItems: 'center',
  },
  txtBuscarGuardia: {
    flex: 1,
    textAlign: 'left',
    marginLeft: 15,
    fontSize: 17,
    fontWeight: '300',
    color: '#c2c2c2',
  },
  isologo: {
    height: 90,
  },
  buscar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '95%',
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#cdcdcd',
    borderRadius: 200,
    height: 50,
    shadowColor: '#d3d3d3',
    shadowOffset: {
      width: 3,
      height: 3,
    },
    shadowOpacity: 0.5,
    shadowRadius: 2,
    marginTop: 10,
  },
  header: {
    width: '100%',
    height: 85,
    position: 'relative',
  },
  medium: {
    width: '100%',
    height: 85,
    alignItems: 'center',
    position: 'relative',
  },
});

const HomeListstyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#00bfa5',
  },
  imgLocation: {
    width: 17.7,
    height: 21.3,
    marginLeft: 10,
  },
  imgComoLlego: {
    width: 23,
    height: 23,
    marginLeft: 15,
  },
  textItemDirection: {
    color: '#2d2d2d',
    fontSize: 13,
    fontWeight: '400',
    marginLeft: 10,
  },
  textItemDirection2: {
    color: '#2d2d2d',
    fontSize: 13,
    fontWeight: '400',
    marginLeft: 5,
  },
  itemButtonsColumna1: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  },
  itemButtonsColumna2: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    width: 180,
  },
  itemButtonsRow: {
    height: 48,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#fafafa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemIcon: {
    borderRadius: 360,
    width: 30,
    height: 30,
    backgroundColor: '#ff6b00',
    position: 'absolute',
    bottom: 16,
    right: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textTituloGuardia: {
    color: '#2d2d2d',
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 10,
    marginLeft: 15,
  },
  textSubTituloGuardia: {
    color: '#2d2d2d',
    fontSize: 13,
    fontWeight: '400',
    marginTop: 5,
    marginLeft: 15,
  },
  imgHospSmall: {
    width: 19,
    height: 13,
  },
  imgHosp: {
    width: 113,
    height: 113,
    marginTop: 15,
    marginLeft: 15,
    borderRadius: 55,
    borderColor: 'black',
  },
  guardiaFila: {
    flexDirection: 'row',
    height: 150,
  },
  guardiaColumna1: {
    width: 130,
  },
  guardiaColumna2: {
    flex: 1,
    justifyContent: 'center',
  },
  itemList: {
    height: 200,
    backgroundColor: '#ffffff',
    width: '94%',
    marginTop: 8,
    borderRadius: 3,
    marginLeft: '3%',
  },
  listContainer: {
    flex: 1,
  },
  list: {
    marginTop: 0,
  },
  texto: {
    width: 100,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtBuscarGuardia: {
    flex: 1,
    textAlign: 'left',
    marginLeft: 5,
    fontSize: 12,
    fontWeight: '400',
    color: '#2d2d2d',
  },
  modal: {
    width: 80,
    height: 100,
  },
  circleClear: {
    width: 45,
    height: 45,
    backgroundColor: 'white',
    borderRadius: 360,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginLeft: 13,
    shadowColor: '#00ab95',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  circle: {
    width: 45,
    height: 45,
    backgroundColor: 'white',
    borderRadius: 360,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginLeft: 13,
    shadowColor: '#00ab95',
    shadowOffset: { width: 1, height: 1 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  imgCloseHome: {
    width: 13,
    height: 13,
  },
  imgIso2: {
    width: 19,
    height: 22,
  },
  iconSearch: {
    marginLeft: 20,
  },
  imgSearch: {
    width: 31,
    height: 31,
    resizeMode: 'stretch',
    alignItems: 'center',
    marginLeft: 0,
  },
  clear: {
    height: 90,
  },
  isologo: {
    height: 90,
  },
  buscar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 160,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ececec',
    borderRadius: 200,
    height: 45,
    shadowColor: '#00ab95',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    marginTop: 20,
    marginLeft: 10,
  },
  columna1: {
    flex: 1,
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  columna2: {
    flex: 1,
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  header: {
    width: '100%',
    height: 85,
    flexDirection: 'row',
  },
  searchButtons: {
    width: '100%',
    height: 70,
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  footer: {
    flexDirection: 'row',
    height: 100,
    justifyContent: 'flex-end',
  },
});

const HomeMapStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  markerBorder4: {
    borderRadius: 360,
    backgroundColor: 'rgba(0,191,165,0.2)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },

  marker4: {
    borderRadius: 360,
    backgroundColor: '#00bfa5',
    width: 46,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hospmarker: {
    width: 26,
    height: 18,
  },
  markerBorder1: {
    borderRadius: 360,
    backgroundColor: 'rgba(32,100,232,0.2)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  marker1: {
    borderRadius: 360,
    backgroundColor: '#2064e8',
    width: 46,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markerBorder2: {
    borderRadius: 360,
    backgroundColor: 'rgba(255,107,0,0.2)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },

  marker2: {
    borderRadius: 360,
    backgroundColor: '#ff6b00',
    width: 46,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markerBorder3: {
    borderRadius: 360,
    backgroundColor: 'rgba(229,28,35,0.2)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },

  marker3: {
    borderRadius: 360,
    backgroundColor: '#e51c23',
    width: 46,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },

  markerBorderPharmacy: {
    borderRadius: 360,
    backgroundColor: 'rgba(149,167,175,0.2)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },

  markerPharmacy: {
    borderRadius: 360,
    backgroundColor: '#95a7af',
    width: 46,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markerBorder: {
    borderRadius: 360,
    backgroundColor: 'rgba(0,191,165,0.2)',
    width: 70,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
  },
  marker: {
    borderRadius: 360,
    backgroundColor: '#00bfa5',
    width: 46,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
  },
  farmmarker: {
    width: 18,
    height: 18,
  },
  map: {
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    position: 'absolute',
    zIndex: 0,
  },
  modalButton: {
    width: 80,
    height: 100,
    position: 'absolute',
    bottom: 10,
    right: 10,
    zIndex: 2,
  },
  circleButton: {
    width: 66,
    height: 66,
    backgroundColor: '#00bfa5',
    borderRadius: 360,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 0,
    shadowColor: '#ececec',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  modal: {
    width: 80,
    height: 100,
  },
  circleClear: {
    width: 45,
    height: 45,
    backgroundColor: 'white',
    borderRadius: 360,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginLeft: 13,
    shadowColor: '#ececec',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  circle: {
    width: 45,
    height: 45,
    backgroundColor: '#00bfa5',
    borderRadius: 360,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    marginLeft: 13,
    shadowColor: '#ececec',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    borderWidth: 1,
    borderColor: '#ececec',
  },
  imgCloseHome: {
    width: 13,
    height: 13,
  },
  imgButtonLista: {
    width: 26,
    height: 31,
  },
  imgIso2: {
    width: 19,
    height: 22,
  },
  iconSearch: {
    marginLeft: 20,
  },
  txtBuscarGuardia: {
    flex: 1,
    textAlign: 'left',
    marginLeft: 5,
    fontSize: 12,
    fontWeight: '400',
    color: '#2d2d2d',
  },
  clear: {
    height: 90,
  },
  isologo: {
    height: 90,
  },
  columna1: {
    flex: 1,
    justifyContent: 'flex-start',
    flexDirection: 'row',
  },
  columna2: {
    flex: 1,
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  header: {
    width: '100%',
    height: 85,
    flexDirection: 'row',
    zIndex: 1,
  },
  medium: {
    width: '100%',
    height: 90,
    justifyContent: 'flex-start',
    flexDirection: 'row',
    zIndex: 1,
  },
});


export { Homestyles, HomeListstyles, HomeMapStyles };
